In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,20,10)
arr

array([17,  7,  4, 13,  2,  4, 18,  5,  4, 16])

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[17,  7,  4, 13,  2],
       [ 4, 18,  5,  4, 16]])

### max()

In [16]:
arr.max() #Retoma el maximo valor

13

In [17]:
matriz.max(1) #Especificamos el eje -> Fila

array([13,  9])

In [18]:
matriz.max(0) #Columna

array([13,  9,  7, 10,  6])

### argmax()

In [19]:
arr.argmax() #Indice del valor maximo

0

In [21]:
matriz.argmax(0) #Columna

array([0, 1, 0, 0, 0], dtype=int64)

### min()

In [22]:
arr.min()

1

In [23]:
matriz.min(0)

array([5, 4, 7, 4, 1])

### argmin()

In [24]:
arr.argmin()

9

In [25]:
matriz.argmin(1)

array([1, 4], dtype=int64)

In [27]:
arr

array([13,  4,  7, 10,  6,  5,  9,  7,  4,  1])

### ptp()

In [28]:
arr.ptp() #Peek to peek, la diferencia entre el numero mas alto y el mas bajo

12

In [29]:
matriz.ptp(0)

array([8, 5, 0, 6, 5])

### np.percentile()

In [32]:
np.percentile(arr,50) # El valor que se encuentra en la mitad

6.5

In [34]:
np.percentile(arr,0) #EL valor mas bajo

1.0

In [36]:
np.percentile(arr,100) #El numero mas bajo

13.0

### .sort()

In [5]:
arr.sort() #Ordena el array
arr

array([ 2,  4,  4,  4,  5,  7, 13, 16, 17, 18])

### np.median()

In [38]:
np.median(arr) #La mediana de un array

6.5

In [40]:
np.median(matriz,0) #La mediana por el eje 0 -> Columnas

array([4. , 5.5, 6.5, 7.5, 9.5])

### np.std()

In [45]:
np.std(arr) #La desviacion estandar

3.261901286060018

### np.var()

In [ ]:
np.var(arr) #La varianza

### np.mean()

In [46]:
np.mean(arr) #La media -> Promedio

6.6

In [47]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [49]:
b = np.array([5,6])
b

array([5, 6])

### np.concatenate()

In [50]:
np.concatenate((a,b),axis = 0) #Error por que son de distintas dimensiones

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [52]:
a.ndim
b.ndim

1

In [53]:
b = np.expand_dims(b,axis = 0)


In [54]:
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
np.concatenate((a,b),axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [56]:
np.concatenate((a,b.T),axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

### .T

In [57]:
b.T  #Invierte la matriz

array([[5],
       [6]])