In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
trozo_de_arr = arr[0:6] #Sigue haciendo refrencia a arr

In [5]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [6]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

### copy()

In [7]:
arr_copy = arr.copy() #Estos dos objetos son distintos a diferencia del slice
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [8]:
arr_copy[:] = 100 
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

# Se debe utilizar el copy para poder realizar cambios sin temor a dañar el array