In [1]:
import numpy as np

### Creamos un array mediante la coleccion range

In [2]:
np.arange(0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,10,2) #Se le da un step de 2 (Start,Stop,Step)

array([0, 2, 4, 6, 8])

### Creamos un array mediante ceros y unos

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((10,10)) #Muy util para definir estructuras previamente

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Funcion linspace

In [9]:
np.linspace(0,10,10) #(Start,Stop, cuantos datos generar)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### Funcion eye

In [10]:
np.eye(4) #Util para la algebra lineal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [11]:
np.random.rand() #Genera n valor aleatorio entre 0 y 1

0.9322647245619209

In [13]:
np.random.rand(4) #Genera un array con 4 numeros aleatroios entre 0 y 1

array([0.79888219, 0.15672381, 0.83726806, 0.43051238])

In [14]:
np.random.rand(4,4) #Genera una matriz con numeros aleatorios entre 0 y 1

array([[0.01020217, 0.28703787, 0.46295294, 0.90104968],
       [0.60494258, 0.03372331, 0.7395761 , 0.62767132],
       [0.46616337, 0.20331331, 0.84393694, 0.01541648],
       [0.49726714, 0.5710338 , 0.83318375, 0.58860914]])

In [15]:
np.random.randint(1,15) #Genera un numero aleatorio entre los parametros elegidos

13

In [17]:
np.random.randint(1,15,(10,10)) #Genera una matriz con los valores aleatorios entre 1 y 15

array([[ 4,  9,  4,  5,  4, 13,  3,  9,  5,  2],
       [ 3,  8,  8,  4, 13,  2, 12, 10,  3,  3],
       [14,  5,  5, 10,  6,  4, 14,  9,  4,  7],
       [13,  5, 12, 11, 10, 10,  6, 11,  6, 13],
       [14, 12,  1, 13,  6, 10, 12, 12, 13, 12],
       [10,  1,  8,  2,  4,  8,  4,  3,  2, 14],
       [ 3,  3,  4,  2,  3,  6, 12, 12,  7, 10],
       [ 9, 13,  8,  9, 14,  7, 14,  8,  1, 12],
       [ 5,  9, 11,  8,  9,  7,  9, 14, 12, 10],
       [10,  3,  1, 11,  7,  2,  7,  8,  1,  9]])