In [1]:
import numpy as np

## Shape y reshape

In [4]:
arr = np.random.randint(1,10,(3,2)) #Generamos un array de numeros aleatorios

In [5]:
arr.shape #Nos muestra las filas y columnas que tenemos

(3, 2)

In [7]:
arr

array([[9, 4],
       [6, 8],
       [6, 1]])

In [8]:
arr.reshape(1,6) #Modificamos la forma del array

array([[9, 4, 6, 8, 6, 1]])

In [9]:
arr.reshape(2,3)

array([[9, 4, 6],
       [8, 6, 1]])

In [10]:
np.reshape(arr,(1,6))

array([[9, 4, 6, 8, 6, 1]])

In [11]:
arr

array([[9, 4],
       [6, 8],
       [6, 1]])

In [12]:
np.reshape(arr,(2,3),"C") #Cambiamos la forma mediante el lenguaje C (Por filas)

array([[9, 4, 6],
       [8, 6, 1]])

In [13]:
np.reshape(arr,(2,3),"F") #Cambiamos la forma mediante el lenguaje Fortran (Por columnas)

array([[9, 6, 8],
       [6, 4, 1]])

In [14]:
np.reshape(arr,(2,3),"A") #Cambiamos la forma mediante a como mejor este optimizado el almacenamiento en mi sistema

array([[9, 4, 6],
       [8, 6, 1]])

# Se pueden realizar estas funciones siempre y cuando se respeten las dimensiones